name: cookbook
description: A simple flutter cookbook app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: ^2.2.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  uuid: ^3.0.4
  permission_handler: ^10.0.0
  reorderables: ^0.5.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/icon.png
    - assets/icons/icon-background.png
    - assets/icons/icon-foreground.png
    - assets/images/no-image.png
    - assets/images/pizza-sauce-1.jpg
    - assets/images/pizza-sauce-2.jpg
    - assets/images/vanilla-ice-cream-1.jpg
    - assets/images/vanilla-ice-cream-2.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/icon-background.png"
  adaptive_icon_foreground: "assets/icons/icon-foreground.png"
